-- ═══════════════════════════════════════════════════════════════════════════════
-- OVERWATCH V3 — Consolidated Deployment Script
-- ═══════════════════════════════════════════════════════════════════════════════
--
-- This single file deploys the complete OVERWATCH Snowflake infrastructure.
-- Run sections in order. Each section is idempotent (safe to rerun).
--
-- Deployment order:
--   1. RBAC (roles and grants)
--   2. Runtime objects (database, schema, warehouse, resource monitor)
--   3. Configuration tables (settings, company scope, owner directory)
--   4. Operational tables (action queue, alerts, audit, recovery)
--   5. Forward platform governance (futures controls, evidence)
--   6. Cost verification (savings, chargeback)
--   7. Dynamic Tables (optional — replaces task-based refresh)
--   8. Scheduled tasks (alert delivery, morning brief)
--
-- Prerequisites:
--   - ACCOUNTADMIN or SYSADMIN role
--   - Snowflake Enterprise Edition (for Dynamic Tables and Access History)
--
-- ═══════════════════════════════════════════════════════════════════════════════


-- ═════════════════════════════════════════════════════════════════════════════
-- SECTION 1: RBAC
-- ═════════════════════════════════════════════════════════════════════════════

CREATE ROLE IF NOT EXISTS OVERWATCH_APP_ROLE
  COMMENT = 'Runtime role for OVERWATCH Streamlit app. Read monitoring views, write action queue.';
CREATE ROLE IF NOT EXISTS OVERWATCH_ADMIN_ROLE
  COMMENT = 'Admin role for OVERWATCH mart setup, task management, and schema migrations.';
CREATE ROLE IF NOT EXISTS OVERWATCH_READER_ROLE
  COMMENT = 'Read-only role for OVERWATCH dashboard consumers without write access.';

GRANT ROLE OVERWATCH_READER_ROLE TO ROLE OVERWATCH_APP_ROLE;
GRANT ROLE OVERWATCH_APP_ROLE TO ROLE OVERWATCH_ADMIN_ROLE;
GRANT ROLE OVERWATCH_ADMIN_ROLE TO ROLE SYSADMIN;


-- ═════════════════════════════════════════════════════════════════════════════
-- SECTION 2: RUNTIME OBJECTS
-- ═════════════════════════════════════════════════════════════════════════════

CREATE DATABASE IF NOT EXISTS DBA_MAINT_DB;
CREATE SCHEMA IF NOT EXISTS DBA_MAINT_DB.OVERWATCH;

CREATE WAREHOUSE IF NOT EXISTS OVERWATCH_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  STATEMENT_TIMEOUT_IN_SECONDS = 600
  COMMENT = 'Dedicated warehouse for OVERWATCH Streamlit app runtime.';

CREATE RESOURCE MONITOR IF NOT EXISTS OVERWATCH_WH_RM
  WITH CREDIT_QUOTA = 50
       FREQUENCY = MONTHLY
       START_TIMESTAMP = IMMEDIATELY
       TRIGGERS ON 80 PERCENT DO NOTIFY
                ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE IF EXISTS OVERWATCH_WH SET RESOURCE_MONITOR = OVERWATCH_WH_RM;

-- Grants
GRANT USAGE ON DATABASE DBA_MAINT_DB TO ROLE OVERWATCH_APP_ROLE;
GRANT USAGE ON SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE OVERWATCH_APP_ROLE;
GRANT USAGE ON DATABASE SNOWFLAKE TO ROLE OVERWATCH_APP_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE OVERWATCH_APP_ROLE;
GRANT USAGE ON WAREHOUSE OVERWATCH_WH TO ROLE OVERWATCH_APP_ROLE;
GRANT MONITOR ON WAREHOUSE OVERWATCH_WH TO ROLE OVERWATCH_APP_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE OVERWATCH_ADMIN_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE OVERWATCH_READER_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE OVERWATCH_READER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE OVERWATCH_READER_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE OVERWATCH_READER_ROLE;
GRANT USAGE ON DATABASE DBA_MAINT_DB TO ROLE OVERWATCH_READER_ROLE;
GRANT USAGE ON SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE OVERWATCH_READER_ROLE;
GRANT USAGE ON WAREHOUSE OVERWATCH_WH TO ROLE OVERWATCH_READER_ROLE;

USE DATABASE DBA_MAINT_DB;
USE SCHEMA OVERWATCH;


-- ═════════════════════════════════════════════════════════════════════════════
-- SECTION 3: CONFIGURATION TABLES
-- ═════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS OVERWATCH_SETTINGS (
  SETTING_NAME   VARCHAR(200) PRIMARY KEY,
  SETTING_VALUE  VARCHAR(4000),
  SETTING_TYPE   VARCHAR(50),
  DESCRIPTION    VARCHAR(1000),
  UPDATED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY     VARCHAR(200) DEFAULT CURRENT_USER()
);

CREATE TABLE IF NOT EXISTS OVERWATCH_SCHEMA_MIGRATION (
  MIGRATION_VERSION VARCHAR(100) NOT NULL,
  MIGRATION_NAME    VARCHAR(300) NOT NULL,
  APPLIED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  APPLIED_BY        VARCHAR(200) DEFAULT CURRENT_USER(),
  SOURCE_FILE       VARCHAR(500),
  NOTES             VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS OVERWATCH_COMPANY_SCOPE (
  COMPANY        VARCHAR(100) NOT NULL,
  SCOPE_TYPE     VARCHAR(100) NOT NULL,
  SCOPE_PATTERN  VARCHAR(500) NOT NULL,
  MATCH_MODE     VARCHAR(20) DEFAULT 'ILIKE',
  ENVIRONMENT    VARCHAR(50),
  IS_ACTIVE      BOOLEAN DEFAULT TRUE,
  NOTES          VARCHAR(1000),
  CREATED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CREATED_BY     VARCHAR(200) DEFAULT CURRENT_USER()
);

CREATE TABLE IF NOT EXISTS OVERWATCH_OWNER_DIRECTORY (
  OWNER_KEY          VARCHAR(200) PRIMARY KEY,
  ENTITY_TYPE        VARCHAR(100),
  ENTITY_PATTERN     VARCHAR(500),
  OWNER_NAME         VARCHAR(200),
  OWNER_EMAIL        VARCHAR(500),
  ONCALL_PRIMARY     VARCHAR(200),
  ONCALL_SECONDARY   VARCHAR(200),
  APPROVAL_GROUP     VARCHAR(200),
  ESCALATION_TARGET  VARCHAR(200),
  DEFAULT_ROUTE      VARCHAR(200),
  SERVICE_TIER       VARCHAR(50),
  MATCH_PRIORITY     NUMBER DEFAULT 0,
  IS_ACTIVE          BOOLEAN DEFAULT TRUE,
  UPDATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY         VARCHAR(200) DEFAULT CURRENT_USER(),
  NOTES              VARCHAR(2000)
);

CREATE TABLE IF NOT EXISTS OVERWATCH_OWNER_TAG_NAMES (
  TAG_NAME    VARCHAR(300) PRIMARY KEY,
  OWNER_TYPE  VARCHAR(100),
  PRIORITY    NUMBER,
  IS_ACTIVE   BOOLEAN DEFAULT TRUE,
  NOTES       VARCHAR(1000),
  UPDATED_AT  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY  VARCHAR(200) DEFAULT CURRENT_USER()
);

CREATE TABLE IF NOT EXISTS OVERWATCH_ANNOTATIONS (
  ANNOTATION_ID   NUMBER AUTOINCREMENT PRIMARY KEY,
  CREATED_BY      VARCHAR(200),
  CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  ENTITY          VARCHAR(500),
  ENTITY_TYPE     VARCHAR(50),
  WINDOW_START    TIMESTAMP_NTZ NOT NULL,
  WINDOW_END      TIMESTAMP_NTZ NOT NULL,
  ANNOTATION_TYPE VARCHAR(100),
  DESCRIPTION     VARCHAR(2000),
  SUPPRESS_ALERTS BOOLEAN DEFAULT TRUE,
  ACTIVE          BOOLEAN DEFAULT TRUE
);


-- ═════════════════════════════════════════════════════════════════════════════
-- SECTION 4: OPERATIONAL TABLES
-- ═════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS OVERWATCH_ALERTS (
  ALERT_ID    NUMBER AUTOINCREMENT PRIMARY KEY,
  CREATED_AT  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  SEVERITY    VARCHAR(20),
  CATEGORY    VARCHAR(100),
  ENTITY_TYPE VARCHAR(100),
  ENTITY_NAME VARCHAR(500),
  STATUS      VARCHAR(40) DEFAULT 'NEW',
  FINDING     VARCHAR(4000),
  OWNER       VARCHAR(200),
  TICKET_ID   VARCHAR(200),
  RESOLVED_AT TIMESTAMP_NTZ,
  RESOLVED_BY VARCHAR(200),
  NOTES       VARCHAR(2000)
);

CREATE TABLE IF NOT EXISTS OVERWATCH_ACTION_QUEUE (
  ACTION_ID                VARCHAR(64) PRIMARY KEY,
  CREATED_AT               TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT               TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  SOURCE                   VARCHAR(100),
  CATEGORY                 VARCHAR(100),
  SEVERITY                 VARCHAR(20),
  ENTITY_TYPE              VARCHAR(100),
  ENTITY_NAME              VARCHAR(500),
  OWNER                    VARCHAR(200),
  STATUS                   VARCHAR(40) DEFAULT 'New',
  FINDING                  VARCHAR(4000),
  RECOMMENDED_ACTION       VARCHAR(4000),
  EST_MONTHLY_SAVINGS      FLOAT,
  GENERATED_SQL_FIX        VARCHAR(8000),
  PROOF_QUERY              VARCHAR(8000),
  COMPANY                  VARCHAR(100),
  ENVIRONMENT              VARCHAR(100),
  TICKET_ID                VARCHAR(200),
  APPROVER                 VARCHAR(200),
  DUE_DATE                 DATE,
  VERIFICATION_STATUS      VARCHAR(40) DEFAULT 'Pending',
  VERIFICATION_QUERY       VARCHAR(8000),
  VERIFICATION_RESULT      VARCHAR(8000),
  BASELINE_VALUE           FLOAT,
  CURRENT_VALUE            FLOAT,
  MEASURED_DELTA           FLOAT,
  VERIFIED_BY              VARCHAR(200),
  VERIFIED_AT              TIMESTAMP_NTZ,
  OWNER_EMAIL              VARCHAR(500),
  OWNER_SOURCE             VARCHAR(200),
  FIXED_BY                 VARCHAR(200),
  FIXED_AT                 TIMESTAMP_NTZ,
  LAST_SEEN_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  SEEN_COUNT               NUMBER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS OVERWATCH_USAGE_LOG (
  RUN_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
  LOG_TIME        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  SF_USER         VARCHAR(200),
  SF_ROLE         VARCHAR(200),
  COMPANY_VIEW    VARCHAR(100),
  SECTION         VARCHAR(200),
  QUERY_DURATION_MS NUMBER,
  APP_VERSION     VARCHAR(20) DEFAULT '3.0',
  EVENT_TYPE      VARCHAR(50) DEFAULT 'SECTION_LOAD',
  ROW_COUNT       NUMBER,
  RESULT_MB       NUMBER(18,4),
  MESSAGE         VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS OVERWATCH_ADMIN_ACTION_AUDIT (
  ACTION_ID        NUMBER AUTOINCREMENT PRIMARY KEY,
  ACTION_TS        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  COMPANY          VARCHAR(100),
  ENVIRONMENT      VARCHAR(50),
  SNOWFLAKE_USER   VARCHAR(200),
  SNOWFLAKE_ROLE   VARCHAR(200),
  ACTION_TYPE      VARCHAR(100),
  TARGET_OBJECT    VARCHAR(1000),
  SQL_TEXT         VARCHAR,
  RESULT_STATUS    VARCHAR(40),
  RESULT_MESSAGE   VARCHAR(4000)
);

CREATE TABLE IF NOT EXISTS OVERWATCH_LOAD_AUDIT (
  LOAD_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
  LOAD_NAME        VARCHAR(200),
  LOAD_STARTED_AT  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  LOAD_FINISHED_AT TIMESTAMP_NTZ,
  STATUS           VARCHAR(40),
  ROWS_LOADED      NUMBER,
  MESSAGE          VARCHAR(4000)
);

CREATE TABLE IF NOT EXISTS OVERWATCH_DBA_CHECKLIST_HISTORY (
  CHECKLIST_ID NUMBER AUTOINCREMENT PRIMARY KEY,
  CHECK_DATE   DATE DEFAULT CURRENT_DATE(),
  ITEM_NAME    VARCHAR(200),
  STATUS       VARCHAR(40),
  CHECKED_BY   VARCHAR(200) DEFAULT CURRENT_USER(),
  NOTES        VARCHAR(2000)
);


-- ═════════════════════════════════════════════════════════════════════════════
-- SECTION 5: FORWARD PLATFORM GOVERNANCE
-- ═════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS OVERWATCH_PLATFORM_FUTURES_CONTROL_REGISTER (
  CONTROL_ID          VARCHAR(200) PRIMARY KEY,
  CONTROL_AREA        VARCHAR(200),
  OWNER               VARCHAR(200),
  OWNER_KEY           VARCHAR(200),
  APPROVAL_GROUP      VARCHAR(200),
  PRIMARY_EVIDENCE    VARCHAR(1000),
  SOURCE_OBJECTS      VARCHAR(1000),
  RISK_IF_MISSING     VARCHAR(2000),
  DBA_DECISION        VARCHAR(2000),
  AUTOMATION_BOUNDARY VARCHAR(2000),
  MATCH_PRIORITY      NUMBER DEFAULT 0,
  IS_ACTIVE           BOOLEAN DEFAULT TRUE,
  UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY          VARCHAR(200) DEFAULT CURRENT_USER()
);

CREATE TABLE IF NOT EXISTS OVERWATCH_PLATFORM_FUTURES_EVIDENCE (
  EVIDENCE_ID        NUMBER AUTOINCREMENT PRIMARY KEY,
  CAPTURED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONTROL_ID         VARCHAR(200),
  CONTROL_AREA       VARCHAR(200),
  ENTITY_TYPE        VARCHAR(200),
  ENTITY_NAME        VARCHAR(500),
  COMPANY            VARCHAR(100),
  ENVIRONMENT        VARCHAR(100),
  SEVERITY           VARCHAR(40),
  FINDING            VARCHAR(4000),
  OWNER              VARCHAR(200),
  APPROVAL_STATUS    VARCHAR(100),
  TICKET_ID          VARCHAR(200),
  VERIFICATION_QUERY VARCHAR(8000),
  VERIFICATION_RESULT VARCHAR(8000),
  CAPTURED_BY        VARCHAR(200) DEFAULT CURRENT_USER(),
  NOTES              VARCHAR(4000)
);

CREATE TABLE IF NOT EXISTS OVERWATCH_WORKLOAD_RECOVERY_AUDIT (
  RECOVERY_AUDIT_ID   NUMBER AUTOINCREMENT PRIMARY KEY,
  RECOVERY_AUDIT_TS   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  ACTION_ID           VARCHAR(64),
  ENTITY_TYPE         VARCHAR(100),
  ENTITY_NAME         VARCHAR(500),
  OWNER               VARCHAR(200),
  RECOVERY_SLA_STATE  VARCHAR(100),
  RECOVERY_SLA_HOURS  FLOAT,
  ACTION_TAKEN        VARCHAR(4000),
  VERIFICATION_RESULT VARCHAR(8000),
  EXECUTED_BY         VARCHAR(200) DEFAULT CURRENT_USER(),
  NOTES               VARCHAR(4000)
);


-- ═════════════════════════════════════════════════════════════════════════════
-- SECTION 6: COST VERIFICATION
-- ═════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS OVERWATCH_COST_SAVINGS_VERIFICATION_RUN (
  RUN_ID                 NUMBER AUTOINCREMENT PRIMARY KEY,
  RUN_TS                 TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  ACTION_ID              VARCHAR(64),
  ENTITY_NAME            VARCHAR(500),
  BASELINE_VALUE         FLOAT,
  POST_PERIOD_VALUE      FLOAT,
  MEASURED_DELTA         FLOAT,
  EST_MONTHLY_SAVINGS    FLOAT,
  VERIFICATION_OUTCOME   VARCHAR(100),
  SOURCE_QUERY           VARCHAR(8000)
);

CREATE TABLE IF NOT EXISTS OVERWATCH_BOOKMARKS (
  BOOKMARK_ID   NUMBER AUTOINCREMENT PRIMARY KEY,
  CREATED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CREATED_BY    VARCHAR(200) DEFAULT CURRENT_USER(),
  BOOKMARK_NAME VARCHAR(200),
  SECTION       VARCHAR(200),
  STATE_JSON    VARCHAR,
  IS_SHARED     BOOLEAN DEFAULT FALSE,
  USE_COUNT     NUMBER DEFAULT 0
);


-- ═════════════════════════════════════════════════════════════════════════════
-- SECTION 7: DYNAMIC TABLES (Optional — Enterprise Edition)
-- ═════════════════════════════════════════════════════════════════════════════
-- Uncomment to deploy Dynamic Tables that replace task-based refresh.

/*
CREATE OR REPLACE DYNAMIC TABLE DT_OVERWATCH_DAILY_CREDITS
  TARGET_LAG = '1 hour' WAREHOUSE = OVERWATCH_WH AS
  SELECT DATE(start_time) AS usage_date, warehouse_name,
         ROUND(SUM(COALESCE(credits_used, 0)), 4) AS total_credits
  FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
  WHERE start_time >= DATEADD('day', -90, CURRENT_TIMESTAMP())
  GROUP BY usage_date, warehouse_name;

CREATE OR REPLACE DYNAMIC TABLE DT_OVERWATCH_TASK_FAILURES
  TARGET_LAG = '1 hour' WAREHOUSE = OVERWATCH_WH AS
  SELECT DATE(scheduled_time) AS failure_date, database_name, schema_name,
         name AS task_name, state, COUNT(*) AS run_count,
         COUNT_IF(state='FAILED') AS failure_count
  FROM SNOWFLAKE.ACCOUNT_USAGE.TASK_HISTORY
  WHERE scheduled_time >= DATEADD('day', -35, CURRENT_TIMESTAMP())
  GROUP BY failure_date, database_name, schema_name, task_name, state;

CREATE OR REPLACE DYNAMIC TABLE DT_OVERWATCH_SERVICE_COSTS
  TARGET_LAG = '2 hours' WAREHOUSE = OVERWATCH_WH AS
  SELECT DATE(start_time) AS usage_date, UPPER(COALESCE(service_type,'UNKNOWN')) AS service_type,
         ROUND(SUM(COALESCE(credits_used,0)),4) AS total_credits
  FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY
  WHERE start_time >= DATEADD('day', -90, CURRENT_TIMESTAMP())
  GROUP BY usage_date, service_type;
*/


-- ═════════════════════════════════════════════════════════════════════════════
-- SECTION 8: MIGRATION LEDGER
-- ═════════════════════════════════════════════════════════════════════════════

MERGE INTO OVERWATCH_SCHEMA_MIGRATION tgt
USING (
  SELECT
    '2026.06.10-consolidated-deploy' AS MIGRATION_VERSION,
    'Consolidated OVERWATCH deployment (RBAC + Mart + DT + Governance)' AS MIGRATION_NAME,
    'snowflake/DEPLOY.sql' AS SOURCE_FILE,
    'Single-file deployment combining RBAC, mart tables, governance, Dynamic Tables, and cost verification.' AS NOTES
) src
ON tgt.MIGRATION_VERSION = src.MIGRATION_VERSION
WHEN NOT MATCHED THEN INSERT (MIGRATION_VERSION, MIGRATION_NAME, SOURCE_FILE, NOTES)
VALUES (src.MIGRATION_VERSION, src.MIGRATION_NAME, src.SOURCE_FILE, src.NOTES);

-- ═══════════════════════════════════════════════════════════════════════════════
-- DEPLOYMENT COMPLETE
-- Next: Assign roles to users:
--   GRANT ROLE OVERWATCH_APP_ROLE TO USER <streamlit_app_user>;
--   GRANT ROLE OVERWATCH_ADMIN_ROLE TO USER <dba_user>;
--   GRANT ROLE OVERWATCH_READER_ROLE TO USER <executive_user>;
-- ═══════════════════════════════════════════════════════════════════════════════
